In [1]:
import pickle
import numpy as np

In [4]:
ohe=pickle.load(open('MODELS/ohe.pkl','rb'))
ohe_sex = pickle.load(open('MODELS/ohe_sex.pkl','rb'))
clf=pickle.load(open('MODELS/clf.pkl','rb'))

In [5]:
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)
#np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [6]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [18]:
test_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_age = test_input[:,2].reshape(1,1)
test_sex,test_input_age

(array([[0., 1.]]), array([[31.0]], dtype=object))

In [22]:
test_enbarked=ohe.transform(test_input[:,-1].reshape(1,1))
test_enbarked

array([[0., 0., 1., 0.]])

In [27]:
test_rem=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_sex,test_enbarked),axis=1)

In [29]:
test_rem.shape

(1, 11)

In [30]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_sex,test_enbarked),axis=1)

In [31]:
test_input_transformed.shape

(1, 11)

In [32]:
clf.predict(test_rem)

array([1], dtype=int64)